ScopeFun:
    stage: build
    tags:
        - ScopeFun
    script:
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" ..
        - msys 
        - mingw32-make package
