stages:
  - build
  - package
  
ScopeFun-exe:
    stage: build
    tags:
        - ScopeFun
    artifacts:
      paths: 
         - sfBuild/*.exe
         - sfBuild/*.sha512
    script:
        - powershell New-Item -ItemType Directory -name sfBuild -Force
        - cd sfBuild
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" ..
        - set "PATH=%PATH%;c:\msys\1.0\bin"
        - mingw32-make package
        - powershell get-date -format {yyyyMMdd} > date.txt
        - powershell get-date -format {HHmmss}   > time.txt
        - set /p date=<date.txt
        - set /p time=<time.txt
        - mkdir Windows\%date%-%time%
        - copy *.exe    Windows\%date%-%time%
        - copy *.sha512 Windows\%date%-%time%
        - winscp /ini=nul /command "open ftp://%FTP_USERNAME%:%FTP_PASSWORD%@ftp.scopefun.com/ "^
                                   "cd Versions"^
                                   "cd Windows"^
                                   "put Windows\%date%-%time%"^
                                   "close"^
                                   "exit"
        
ScopeFun-Source:
    stage: package
    tags:
        - ScopeFun
    artifacts:
      paths: 
         - sfSource/*.zip
         - sfSource/*.sha512
    script:
        - powershell New-Item -ItemType Directory -name sfSource -Force
        - cd sfSource
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" -D CPACK_SOURCE_7Z="false" ..
        - set "PATH=%PATH%;c:\msys\1.0\bin"
        - mingw32-make package_source
        - powershell get-date -format {yyyyMMdd} > date.txt
        - powershell get-date -format {HHmmss}   > time.txt
        - set /p date=<date.txt
        - set /p time=<time.txt
        - mkdir Windows\%date%-%time%
        - copy  *.zip Windows\%date%-%time%
        - copy  *.sha512 Windows\%date%-%time%
        - winscp /ini=nul /command "open ftp://%FTP_USERNAME%:%FTP_PASSWORD%@ftp.scopefun.com/ "^
                                   "cd Versions"^
                                   "cd Windows"^
                                   "put Windows\%date%-%time%"^
                                   "close"^
                                   "exit"
