ScopeFunCmake:
    stage: build
    tags:
        - ScopeFun
    script:
        - mkdir build
        - cd buildhttps://gitlab.com/sfDavid/ScopeFun/-/jobs/187484570        
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" ..
ScopeFunMake:
    stage: build
    before_script:
        - set "PATH=%PATH%;c:\msys\1.0\bin;c:\TDM-GCC-64\bin"
    tags:
        - ScopeFun
    script:
        - mkdir build
        - cd build
        - mingw32-make package
