Directory:
  stage: build
  script:
    - mkdir build
  allow_failure: true
  
ScopeFun:
    stage: build
    tags:
        - ScopeFun
    script:
        - cd build
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" ..
        - set "PATH=%PATH%;c:\msys\1.0\bin"
        - mingw32-make package_sources
        - mingw32-make package
        - powershell get-date -format {yyyyMMdd} > date.txt
        - powershell get-date -format {HHmmss}   > time.txt
        - set /p date=<date.txt
        - set /p time=<time.txt
        - mkdir Windows\%date%-%time%
        - copy  *.zip Windows\%date%-%time%
        - copy  *.exe Windows\%date%-%time%
        - copy  *.sha512 Windows\%date%-%time%
        - winscp /ini=nul /command "open ftp://%FTP_USERNAME%:%FTP_PASSWORD%@ftp.scopefun.com/ "^
                                   "cd Versions"^
                                   "cd Windows"^
                                   "put Windows\%date%-%time%"^
                                   "close"^
                                   "exit"
