stages:
  - build
  - zip-src
  - ftp-upload
  
Build-Win64:
    stage: build
    tags:
        - ScopeFun
    artifacts:
      name: "ScopeFun-Win64"
      paths: 
         - sfExe/*.exe
         - sfExe/*.sha512
    cache:
      paths: 
         - sfExe/
         - sfSrc/
    script:
        - powershell New-Item -ItemType Directory -name sfExe -Force
        - cd sfExe
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" -D CPACK_SOURCE_ZIP="false" -S .. -B .
        - set "PATH=%PATH%;c:\msys\1.0\bin"
        - mingw32-make package
        - del %cd%\..\bin\*.exe
        - del %cd%\..\bin\*.pyd

Zip-Src:
    stage: zip-src
    tags:
        - ScopeFun
    cache:
      paths: 
         - sfExe/
         - sfSrc/
    dependencies: []
    script:
        - powershell New-Item -ItemType Directory -name sfSrc -Force
        - cd sfSrc
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" -D CPACK_SOURCE_ZIP="false" -S .. -B .
        - set "PATH=%PATH%;c:\msys\1.0\bin"
        - mingw32-make package_source

Upload-Ftp:
    stage: ftp-upload
    tags:
        - ScopeFun
    dependencies: []
    cache:
      paths: 
         - sfExe/
         - sfSrc/
    script:
        - cd sfSrc
        - powershell get-date -format {yyyyMMdd} > date.txt
        - powershell get-date -format {HHmmss}   > time.txt
        - set /p date=<date.txt
        - set /p time=<time.txt
        - mkdir Windows\%date%-%time%
        - copy %cd%\..\sfExe\*.exe     Windows\%date%-%time%
        - copy %cd%\..\sfExe\*.sha512  Windows\%date%-%time%
        - copy *.7z                    Windows\%date%-%time%
        - copy *.sha512                Windows\%date%-%time%
        - winscp /ini=nul /command "open ftp://%FTP_USERNAME%:%FTP_PASSWORD%@ftp.scopefun.com/ "^
                                   "cd Versions"^
                                   "cd Windows"^
                                   "put Windows\%date%-%time%"^
                                   "close"^
                                   "exit"
