ScopeFunCmake:
    stage: build
    tags:
        - ScopeFun
    script:
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" ..
        - mingw32-make package
ScopeFunMake:
    stage: build
    tags:
        - ScopeFun
    variables:
        - PATH: %PATH%;c:/msys/1.0/bin
    script:
        - mkdir build
        - cd build
        - mingw32-make package
